name: Testing workflow

on:
  workflow_dispatch
env:
  cloud: google-cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env: 
      Greeting: hello
    steps: 
     - name: "Say Hello its Monday"
       run: echo"$Greeting $FirstName is usning $cloud"
       env:
         FirstName: shubham
   
