name: Context Variable
on: 
  workflow_dispatch

env:
  cloud: google.cloud
jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Context Variable"
        run: |
         echo "Repo Name: ${{github.repository}}"
         echo "Workflow Name: ${{github.workflow}}"
         echo "TriggerActor Name: ${{github.triggering_actor}}"


